version: 2

# Build documentation with MkDocs
mkdocs:
  configuration: mkdocs.yml

# Optionally set the version of Python and requirements required to build your docs
python:
  install:
    - requirements: docs/requirements.txt

# Specify the build environment
build:
  os: ubuntu-20.04
  tools:
    python: "3.8"